---
title: Maak een materiaal met een textuur
hero_image: images/banner.png
description: Maak een materiaal met een textuur
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - title: Maak een materiaal met een textuur
