title: Create a material with a texture
hero_image: images/banner.png
description: uCreate a material with a texture
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - title: Create a material with a texture
