---
title: Créer un matériau avec une texture
hero_image: images/banner.png
description: Créer un matériau avec une texture
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - title: Créer un matériau avec une texture
